apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-prod
  labels:
    app: taskflow-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec: # <-- Ini spesifikasi untuk Pod template
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: taskflow-api
          image: ghcr.io/yolookings/mycicd-test:stable
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://taskflow:taskflow_secret@taskflow-db-svc.taskflow-prod.svc.cluster.local:5432/taskflow?sslmode=disable"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
